# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

allSubsets0 <- function(x) {
    .Call('gRbase_allSubsets0_cpp', PACKAGE = 'gRbase', x)
}

allSubsets <- function(XX_) {
    .Call('gRbase_allSubsets_cpp', PACKAGE = 'gRbase', XX_)
}

cell2entry_cpp <- function(cell, adim) {
    .Call('gRbase_cell2entry_cpp', PACKAGE = 'gRbase', cell, adim)
}

cell2entry2_cpp <- function(cell, plevels) {
    .Call('gRbase_cell2entry2_cpp', PACKAGE = 'gRbase', cell, plevels)
}

nextCell_cpp <- function(cell, adim) {
    .Call('gRbase_nextCell_cpp', PACKAGE = 'gRbase', cell, adim)
}

nextCellSlicePrim_cpp <- function(cell, adim, sliceIndic) {
    .Call('gRbase_nextCellSlicePrim_cpp', PACKAGE = 'gRbase', cell, adim, sliceIndic)
}

nextCellSlice_cpp <- function(cell, adim, sliceSet) {
    .Call('gRbase_nextCellSlice_cpp', PACKAGE = 'gRbase', cell, adim, sliceSet)
}

slice2entry_cpp <- function(sliceCell, sliceSet, adim) {
    .Call('gRbase_slice2entry_cpp', PACKAGE = 'gRbase', sliceCell, sliceSet, adim)
}

getCellNumberPrim_cpp <- function(cell, perm, pvec) {
    .Call('gRbase_getCellNumberPrim_cpp', PACKAGE = 'gRbase', cell, perm, pvec)
}

getCellNumber_cpp <- function(cell, adim, perm) {
    .Call('gRbase_getCellNumber_cpp', PACKAGE = 'gRbase', cell, adim, perm)
}

permuteCellEntries_cpp <- function(perm, adim) {
    .Call('gRbase_permuteCellEntries_cpp', PACKAGE = 'gRbase', perm, adim)
}

arrayMargin0 <- function(a1, marg_idx) {
    .Call('gRbase_arrayMargin0_cpp', PACKAGE = 'gRbase', a1, marg_idx)
}

arrayMarginChr_cpp <- function(a1, marg) {
    .Call('gRbase_arrayMarginChr_cpp', PACKAGE = 'gRbase', a1, marg)
}

arrayMargin <- function(a1, marg) {
    .Call('gRbase_arrayMargin_cpp', PACKAGE = 'gRbase', a1, marg)
}

extendArrays <- function(a1, a2) {
    .Call('gRbase_extendArrays_cpp', PACKAGE = 'gRbase', a1, a2)
}

extendArrayAlong <- function(a1, a2) {
    .Call('gRbase_extendArrayAlong_cpp', PACKAGE = 'gRbase', a1, a2)
}

alignArrays <- function(a1, a2) {
    .Call('gRbase_alignArrays_cpp', PACKAGE = 'gRbase', a1, a2)
}

alignArrays2 <- function(a1, a2) {
    .Call('gRbase_alignArrays2_cpp', PACKAGE = 'gRbase', a1, a2)
}

arrayOp2 <- function(a1, a2, op = '*') {
    .Call('gRbase_arrayOp2_cpp', PACKAGE = 'gRbase', a1, a2, op)
}

arrayOp <- function(a1, a2, op = '*') {
    .Call('gRbase_arrayOp_cpp', PACKAGE = 'gRbase', a1, a2, op)
}

.extendArrayAlongOLD <- function(a1, a2) {
    .Call('gRbase_extendArrayAlongOLD_cpp', PACKAGE = 'gRbase', a1, a2)
}

.arrayOpOLD <- function(a1, a2, op = '*') {
    .Call('gRbase_arrayOpOLD_cpp', PACKAGE = 'gRbase', a1, a2, op)
}

.arrayOp2OLD <- function(a1, a2, op = '*') {
    .Call('gRbase_arrayOp2OLD_cpp', PACKAGE = 'gRbase', a1, a2, op)
}

getPerm <- function(XX_, perm) {
    .Call('gRbase_getPerm', PACKAGE = 'gRbase', XX_, perm)
}

arrayPerm0 <- function(XX_, perm) {
    .Call('gRbase_arrayPerm0_cpp', PACKAGE = 'gRbase', XX_, perm)
}

arrayPerm <- function(XX_, perm) {
    .Call('gRbase_arrayPerm_cpp', PACKAGE = 'gRbase', XX_, perm)
}

fitLoglin <- function(x, glist, peps = 1e-3) {
    .Call('gRbase_fitLoglin_cpp', PACKAGE = 'gRbase', x, glist, peps)
}

MAT2ftM <- function(XX_) {
    .Call('gRbase_MAT2ftM', PACKAGE = 'gRbase', XX_)
}

SYMMAT2ftM <- function(XX_) {
    .Call('gRbase_SYMMAT2ftM', PACKAGE = 'gRbase', XX_)
}

is_sym_MAT <- function(XX_) {
    .Call('gRbase_is_sym_MAT', PACKAGE = 'gRbase', XX_)
}

matrix2dgCMatrix <- function(XX_) {
    .Call('gRbase_matrix2dgCMatrix', PACKAGE = 'gRbase', XX_)
}

dgCMatrix2matrix <- function(XX_) {
    .Call('gRbase_dgCMatrix2matrix', PACKAGE = 'gRbase', XX_)
}

mcsMAT_ <- function(XX_, OO_) {
    .Call('gRbase_mcsMAT_', PACKAGE = 'gRbase', XX_, OO_)
}

moralizeMAT <- function(XX_) {
    .Call('gRbase_moralizeMAT', PACKAGE = 'gRbase', XX_)
}

propagateLS_cpp <- function(pp_, rip) {
    .Call('gRbase_propagateLS_cpp', PACKAGE = 'gRbase', pp_, rip)
}

rowmat2list <- function(XX_) {
    .Call('gRbase_rowmat2list', PACKAGE = 'gRbase', XX_)
}

colmat2list <- function(XX_) {
    .Call('gRbase_colmat2list', PACKAGE = 'gRbase', XX_)
}

which_matrix_index <- function(XX_) {
    .Call('gRbase_which_matrix_index', PACKAGE = 'gRbase', XX_)
}

solveSPD <- function(X_) {
    .Call('gRbase_solveSPD', PACKAGE = 'gRbase', X_)
}

sp_setXtf1 <- function(XX_, TF_) {
    .Call('gRbase_sp_setXtf1', PACKAGE = 'gRbase', XX_, TF_)
}

topoSortMAT_ <- function(XX_) {
    .Call('gRbase_topoSortMAT_', PACKAGE = 'gRbase', XX_)
}

triangulateMAT_ <- function(XX_, OO_) {
    .Call('gRbase_triangulateMAT_', PACKAGE = 'gRbase', XX_, OO_)
}

dagList2dgCMatrix <- function(LL, vn) {
    .Call('gRbase_dagList2dgCMatrix', PACKAGE = 'gRbase', LL, vn)
}

ugList2dgCMatrix <- function(LL, vn) {
    .Call('gRbase_ugList2dgCMatrix', PACKAGE = 'gRbase', LL, vn)
}

dagList2matrix <- function(LL, vn) {
    .Call('gRbase_dagList2matrix', PACKAGE = 'gRbase', LL, vn)
}

ugList2matrix <- function(LL, vn) {
    .Call('gRbase_ugList2matrix', PACKAGE = 'gRbase', LL, vn)
}

adjList2tfList <- function(LL) {
    .Call('gRbase_adjList2tfList', PACKAGE = 'gRbase', LL)
}

adjList2ftList <- function(LL) {
    .Call('gRbase_adjList2ftList', PACKAGE = 'gRbase', LL)
}

adjList2ftM <- function(LL) {
    .Call('gRbase_adjList2ftM', PACKAGE = 'gRbase', LL)
}

adjList2tfM <- function(LL) {
    .Call('gRbase_adjList2tfM', PACKAGE = 'gRbase', LL)
}

adjList2matrix <- function(LL) {
    .Call('gRbase_adjList2matrix', PACKAGE = 'gRbase', LL)
}

adjList2dgCMatrix <- function(LL) {
    .Call('gRbase_adjList2dgCMatrix', PACKAGE = 'gRbase', LL)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('gRbase_RcppExport_registerCCallable', PACKAGE = 'gRbase')
})
